### PR TITLE
Update all emojis to their latest version

### PR DESCRIPTION
**Pull request by SIkebe**
Updated  all emojis to their latest version.
https://www.webfx.com/tools/emoji-cheat-sheet/

I wrote a very ugly downloader in C# 😅 
```cs
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using AngleSharp;
using AngleSharp.Html.Dom;

var baseUri = "https://www.webfx.com/tools/emoji-cheat-sheet/";
var config = Configuration.Default.WithDefaultLoader();
var document = await BrowsingContext.New(config).OpenAsync(baseUri);
var client = new HttpClient();

var assets = @"path-to-assets\";
var existingFiles = Directory.EnumerateFiles(assets)
    .Select(f => f.Split(Path.DirectorySeparatorChar).Last())
    .ToList();

foreach (var element in document.QuerySelectorAll(@".emojis > li .emoji[data-src]"))
{
    var spanElement = (IHtmlSpanElement)element;
    var name = spanElement.NextElementSibling.InnerHtml;
    if (!existingFiles.Contains($"{name}.png"))
    {
        var image = spanElement.Dataset.Single(d => d.Key == "src").Value;
        var bytes = await client.GetByteArrayAsync($"{baseUri}{image}");
        await File.WriteAllBytesAsync(@$"{assets}{name}.png", bytes);
    }
}

var files = Directory.EnumerateFiles(assets)
    .Select(f => f.Split(Path.DirectorySeparatorChar).Last())
    .Select(f => f.Split('.').First())
    .OrderBy(f => f)
    .ToList();

var builder = new StringBuilder();
builder.Append($@"""{files.First()}"",");

foreach (var file in files.Skip(1))
{
    builder.Append($@"
    ""{file}"",");
}

var embed = builder.ToString().TrimEnd(',');
var emojiUtil = $@"package gitbucket.emoji

/**
 * Converts an Emoji like :smiley: to its related image
 */
object EmojiUtil {{

  val emojis = Set(
    {embed}
  )

  private val emojiPattern = """"""\:[a-z0-9_\-\+]+\:"""""".r

  def convertEmojis(text: String)(implicit context: gitbucket.core.controller.Context): String =
    emojiPattern.replaceAllIn(text, e => {{
      val emoji = e.group(0).replaceAll("":"", """")
      if (!emojis.contains(emoji)) s"":$emoji:""
      else s""""""<img src=""${{context.baseUrl}}/plugin-assets/emoji/${{emoji}}.png"" alt="":$emoji:"" class=""emoji"" />""""""
    }})

}}
";

await File.WriteAllTextAsync(@"path-to-EmojiUtil.scala", emojiUtil);
```

### CODE REVIEW

**Comment by takezoe** [comment]
It would be nice if we can do this by sbt :-)

By the way, some emojis are deleted in this pull request although they are available at GitHub and Cheatsheet. Is this an issue in the download program above?

**Comment by SIkebe** [comment]
>It would be nice if we can do this by sbt :-)

... 😅 

Following emojis are deleted in this PR.
|name|GitHub|Cheatsheet|
|:--|:--|:--|
|109|N/A|N/A|
|black_square|N/A|N/A|
|moon|:moon:|N/A|
|walking|:walking:|N/A|
|white_square|N/A|N/A|
|wink2|N/A|N/A|

>some emojis are deleted in this pull request although they are available at GitHub and Cheatsheet

Could you give me concrete examples? I can't find one.

**Comment by SIkebe** [comment]
These are renamed emojis.
* black_square -> black_large_square
* moon -> crescent_moon
* white_square -> white_large_square

**Comment by takezoe** [comment]
For example, `bento.png` is kept in the source code but the file seems to be deleted.

**Comment by takezoe** [comment]
Ah, these files are replaced with smaller files?

**Comment by SIkebe** [comment]
>Ah, these files are replaced with smaller files?

image
Yeah, some files are modified slightly.

**Comment by takezoe** [comment]
Sorry, I have misread diffs. This looks good to me. Thanks for working on this!

I'll try to translate your script to a sbt task :-)

**Pull request merged**
